version: '3'

services:
  app:
    build: .
    command: .docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
  db: 
    image: mysql:8.0.31-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated